### ISSUE TITLE
push到第二个VC时，不能移动到准确位置

### ISSUE THREAD

**Issue by KittenYang** [boycechang/BCMagicTransition#2]
like this:
![2015-05-04 19_58_49](https://cloud.githubusercontent.com/assets/5517281/7453070/091d3632-f298-11e4-90d7-8ce985ec6fac.gif)

**Comment by KittenYang** [comment]
而且，为什么不能调用ViewDidLoad方法？

**Comment by boycechang** [comment]
在Push之前调用 layoutIfNeeded 即可解决

**Comment by wy19901227** [comment]
解决不了吧，
